version: '3.9'

services:
  web:
    container_name: laravel_web
    image: bitnami/nginx:latest
    restart: always
    ports:
        -   "8082:8083"
    volumes:
      - .:/app
      - ./zdocker/backend_training/training.conf:/opt/bitnami/nginx/conf/server_blocks/traing.conf
    networks:
      - laravel_training
  database:
    container_name: laravel_database
    image: bitnami/mysql:latest
    restart: always
    environment:
        - MYSQL_ROOT_USER=${DB_USERNAME}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./zdocker/database/mysql_training:/bitnami/mysql/data
    networks:
      - laravel_training
  web-fpm:
    container_name: laravel_web_fpm
    image: bitnami/php-fpm:latest
    restart: always
    volumes:
      - .:/app
    networks:
      - laravel_training

  adminer:
    container_name: laravel_adminer
    image: adminer:latest
    restart: always
    networks:
        - laravel_training
    ports:
        -   "1083:8080"
    depends_on:
      - database

volumes:
  mysql_training:
    driver: local

networks:
  laravel_training:
    driver: bridge
