name: Test Install NodeJS
run-name: {{ github.actor }} dispatched this workflow
on: [workflow_dispatch]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g bats
      - run : bats -v
