name: Deploy Staging
on: [workflow_dispatch]
concurrency:
  group: deploy_staging
  cancel-in-progress: true
env:
  WORK_DIR: /home/apps.metafox.app
jobs:
  deploy_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: zip source
        run: |
          rm -rf ./backend_test.zip
          zip -r backend_test.zip *
      - name: deploy to staging site
        uses: burnett01/rsync-deployments@5.2.1
        with:
          path: ./backend_test.zip
          remote_user: ${{ secrets.SSH_USER }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: "${{ env.WORK_DIR }}/backend_test.zip"
      - name: Unzip source
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORK_DIR }}
            mkdir backend_test
            unzip -o backend_test.zip -d backend_test


