name: test-install-nodeJS
run-name: ${{ github.actor }} dispatched this workflow
on: [workflow_dispatch]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clone source from Repository

      - uses: actions/setup-node@v3
        name: Checkout source from 14
        with:
          node-version: 14

      - run: npm install -g bats
        name: Running Story

      - run: bats -v
        name: Get Bat Version
